### PR TITLE
add travis config

### PR DESCRIPTION
**Pull request by ingorichter**
There is no immediate need but I was looking at some of the additions and fixes I'd like to work on in the short term, it would be beneficial to run tests and code coverage on travis to avoid failing.
Unit tests are a recent addition to the project, there is a lot of room to add more tests for future features and the existing code base. The same is still true for code coverage. But we have to start somewhere. :-)

Since I'm not an admin for the repo, it would be great if you could enable travis for the project @ssorallen.

### CODE REVIEW

**Comment by ssorallen** [comment]
Thanks for the Travis config. Travis requires admin access in order to set up the commit hooks, but I am currently only a collaborator.

@jacobSingh How do you feel about making me an admin on this repo? You could also do the Travis setup. Alternatively we could transfer Tab Wrangler into the @tabwrangler organization (I just grabbed the name, I'll invite you and make you an admin if you want to go that route) and administer it from there.

**Comment by ingorichter** [comment]
Any update on this? It would be helpful to get it working in the short term ;-)

**Comment by ssorallen** [comment]
@jacobSingh 🏓

**Comment by ssorallen** [comment]
@jacobSingh Could you make me an admin on this repo?

**Comment by ssorallen** [comment]
@jacobSingh Hey, could you make me an admin here? No more bugging from me after that!

**Comment by ingorichter** [comment]
Oh Boy, I wonder how we can proceed with this PR. I'd like to have travis builds for the future. It would open more possibilities for testing and coverage reporting. I wonder if @jacobSingh ever saw our request to make this happen.

**Comment by ssorallen** [comment]
@ingorichter I was hoping to avoid forking this repository, but I could fork it to my account until @jacobSingh is able to give me admin access on this repo. I'd happily converge back on his fork when I get the necessary access.

**Comment by quintrino** [comment]
I actually think the @tabwrangler organization route is actually a better choice, just in case you @ssorallen also end up with other priorities overtaking this. Has anyone reached out to @jacobSingh  via the Twitter or email listed on his contact page?

**Comment by ssorallen** [comment]
@quintrino It's likely better in the long run to move to the organization anyway.

I tweeted at Jacob.

**Comment by ingorichter** [comment]
I believe the organization route is definitely the better option. I hope @jacobSingh is able to make a decision soon.

**Comment by ssorallen** [comment]
I'll merge this and get the change into [tabwrangler/tabwrangler](https://github.com/tabwrangler/tabwrangler).

**Comment by jacobSingh** [comment]
Yes totally.  I'm in favor :)

**Comment by ssorallen** [comment]
@jacobSingh Okay great, I already added you as an admin to the TabWrangler organization. I will see if I can transfer all current open issues from this repo to tabwrangler/tabwrangler. I'll update the README here to point to the new repo.

I will likely separate the tabwrangler/tabwrangler fork from this repo once all of the transferring is complete since forks are less searchable and less prominent on GitHub than standalone repos.

**Comment by jacobSingh** [comment]
Really sorry to have missed these messages. I was on my holiday at the
time. I don't really program for a living anymore but I get a ton of github
notifications so they are often ignored.

You don't need my permission for anything, you are doing such an amazing
job I'd have no right to withhold it!

If you want to reach me, best is a direct email. (same as my github address
- my name at Gmail)

Best
J

**Comment by ssorallen** [comment]
@ingorichter The repo has now been transferred to the tabwrangler organization. The Travis config is up and running at https://travis-ci.org/tabwrangler/tabwrangler

Let me know if you need any changes on travis-ci.org.

**Pull request merged**
