### PR TITLE
Close #97. min tabs can be now set to 0

### LINKED ISSUE #97: Don't auto-close if I only have X tabs setting does not save "0"
If I set the Don't auto-close if I only have _ tabs setting to 0, it'll default back to 1 the next time I restart chrome

### PR DESCRIPTION
**Pull request by stevenqzhang**
Simple change of making lowerbound exclusive instead of inclusive

### CODE REVIEW

**Comment by stevenqzhang** [comment]
@jacobSingh I've tested this for a few days and seems to fix issue #97

**Comment by ssorallen** [comment]
Would you be willing to update your PR? I will merge it.

**Comment by stevenqzhang** [comment]
Oops, I don't have my github emails forwarding properly and just saw this. Thanks for doing this! @ssorallen

**Comment by ssorallen** [comment]
@stevenqzhang You created the PR a while back, no worries. Thanks for the contribution. I am working on Tab Wrangler now, so if you've got more suggestions or contributions please feel free. I'll merge them.

**Pull request merged**
