### PR TITLE
Remove limit on how long users may want to keep inactive tabs

### PR DESCRIPTION
**Pull request by noweverywhere**

### CODE REVIEW

**Comment by dissolved** [comment]
Yes!

**Comment by ssorallen** [comment]
The check for `> 0` should stick around, otherwise this is reasonable.

**Comment by ssorallen** [comment]
Closing in favor of #94. Removing the upper limit sounds good to me, but the lower one should stick around. I merged #94 because 7200 is a huge number and it kept the lower limit around.

**Comment by ssorallen** [comment]
Thanks for putting this together a while back. I agree your approach was better for the usability of the extension, and I went with your approach in the latest release: https://github.com/tabwrangler/tabwrangler/issues/166

**Pull request closed without merging**
